// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASjafb5n3CY2kynkWmbXL3IjJgmv169EY',
    appId: '1:622702610562:web:85ada7587e0c9386ca4c9b',
    messagingSenderId: '622702610562',
    projectId: 'nefes-a9cfb',
    authDomain: 'nefes-a9cfb.firebaseapp.com',
    storageBucket: 'nefes-a9cfb.firebasestorage.app',
    measurementId: 'G-N718KMNP42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcmBRiSWReTSHXxvLKKZzrZZJFvC_LLPg',
    appId: '1:622702610562:android:1a1276b2a8ea9735ca4c9b',
    messagingSenderId: '622702610562',
    projectId: 'nefes-a9cfb',
    storageBucket: 'nefes-a9cfb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnmlu1_EhiwBy0V4cROlNE6ytT8o06ArM',
    appId: '1:622702610562:ios:33bf7c53ae7e3e6cca4c9b',
    messagingSenderId: '622702610562',
    projectId: 'nefes-a9cfb',
    storageBucket: 'nefes-a9cfb.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnmlu1_EhiwBy0V4cROlNE6ytT8o06ArM',
    appId: '1:622702610562:ios:33bf7c53ae7e3e6cca4c9b',
    messagingSenderId: '622702610562',
    projectId: 'nefes-a9cfb',
    storageBucket: 'nefes-a9cfb.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASjafb5n3CY2kynkWmbXL3IjJgmv169EY',
    appId: '1:622702610562:web:efe13508db20f10eca4c9b',
    messagingSenderId: '622702610562',
    projectId: 'nefes-a9cfb',
    authDomain: 'nefes-a9cfb.firebaseapp.com',
    storageBucket: 'nefes-a9cfb.firebasestorage.app',
    measurementId: 'G-V5JEHS4XLE',
  );
}
